### ISSUE TITLE
Custom locale not working

### ISSUE THREAD

**Issue by aditiohri** [yairEO/relative-time#1]
Hello! This project is awesome.

I am having difficulty successfully changing the locale on my machine. 
I tried your JSFiddle and it works there, but my local code returns the default relative time in English.
Can you please advise?

I am using Node v12.20.1

This is my code:
`const RelativeTime = require("@yaireo/relative-time");`
`const relativeTimeFrench = new RelativeTime({ locale: "fr-ca" });`
`relativeTimeFrench.from(new Date("29 May 2021 00:00:34 +0000"));`

Returns the following:
`23 hours ago`

Thank you!

**Comment by aditiohri** [comment]
Hi! I just updated my version of Node to 14.0.0 and it is working now. I looked up the [MDN spec on the Intl.RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat) to find that only 13 and up are supported. Thanks again for this great package!!

**Comment by yairEO** [comment]
I'm happy it was just a simple thing :)
