### ISSUE TITLE
Doesn't seem to support Leap Years and Leap seconds

### ISSUE THREAD

**Issue by wellonthehill** [yairEO/relative-time#4]
any chance code will be enhanced to support leap years and leap seconds?

**Comment by yairEO** [comment]
How is this possible? 
Code is using the browser API `RelativeTimeFormat`... it should support that.

Do you have any links showing it is not?

**Comment by wellonthehill** [comment]
I would have to go back and review the code again. i've done a million things since then. Most people doing their own calculation (and i've seen lots of code examples) do not take into account leap years and leap seconds. I'll take another look this week. Thanks for responding!

    On Sunday, February 13, 2022, 08:31:56 AM EST, Yair Even Or ***@***.***> wrote:  
 
 


How is this possible? the code is your a browser API RelativeTimeFormat... it should support that.

Do you have any links showing it is not?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
