### ISSUE TITLE
Typescript Definitions are missing

### ISSUE THREAD

**Issue by NatoNathan** [yairEO/relative-time#6]
When you install the package from npm, the typescript definitions although listed in the `package.json` are missing, when you check `node_modules`.

**Comment by yairEO** [comment]
I don't know anything about typescript, what do you think should be done? the file exists,
although I don't remember who helped me create it. I personally loath typescript :)

**Comment by NatoNathan** [comment]
Yeah I did see it in your repo, it's just not present on NPM as you should be able to see here https://www.npmjs.com/package/@yaireo/relative-time?activeTab=code , it is your ’package.json’ too, so as long as the file is present and not ignored with ’.npmignore’ or ’.gitignore’ it should uploaded when you next do a ’npm publish’.

**Comment by yairEO** [comment]
fixed (now) in `v1.0.4`
